# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 20:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=200)),
                ('pendingUserName', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('created', models.DateTimeField(default=datetime.datetime(2016, 11, 24, 20, 21, 32, 816426, tzinfo=utc), verbose_name='date_pendingUser_joined')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=200)),
                ('userName', models.CharField(max_length=200)),
                ('numVotes', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=200)),
                ('created', models.DateTimeField(default=datetime.datetime(2016, 11, 24, 20, 21, 32, 763334, tzinfo=utc), verbose_name='date_user_joined')),
            ],
        ),
    ]
