# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-08 04:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myDream', '0002_auto_20161124_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 8, 4, 21, 51, 810788, tzinfo=utc), verbose_name='date_pendingUser_joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 8, 4, 21, 51, 789876, tzinfo=utc), verbose_name='date_user_joined'),
        ),
    ]
