# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-10 02:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myDream', '0007_auto_20161209_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 10, 2, 51, 49, 677721, tzinfo=utc), verbose_name='date_pendingUser_joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 10, 2, 51, 49, 660197, tzinfo=utc), verbose_name='date_user_joined'),
        ),
    ]
