# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 06:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myDream', '0012_auto_20161215_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 16, 6, 7, 3, 448437, tzinfo=utc), verbose_name='date_pendingUser_joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 16, 6, 7, 3, 439347, tzinfo=utc), verbose_name='date_user_joined'),
        ),
    ]
