# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 01:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myDream', '0015_auto_20161216_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 17, 1, 11, 32, 123304, tzinfo=utc), verbose_name='date_pendingUser_joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 17, 1, 11, 32, 86671, tzinfo=utc), verbose_name='date_user_joined'),
        ),
    ]
