# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 01:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myDream', '0021_auto_20170109_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 11, 1, 57, 9, 738575, tzinfo=utc), verbose_name='date_pendingUser_joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 11, 1, 57, 9, 610317, tzinfo=utc), verbose_name='date_user_joined'),
        ),
    ]
