# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 21:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myDream', '0022_auto_20170110_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 11, 21, 55, 34, 226240, tzinfo=utc), verbose_name='date_pendingUser_joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 11, 21, 55, 33, 990358, tzinfo=utc), verbose_name='date_user_joined'),
        ),
    ]
