# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-21 01:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myDream', '0023_auto_20170111_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 21, 1, 4, 0, 572021, tzinfo=utc), verbose_name='date_pendingUser_joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 21, 1, 4, 0, 337093, tzinfo=utc), verbose_name='date_user_joined'),
        ),
    ]
