# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-18 01:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myDream', '0024_auto_20170520_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 1, 0, 36, 233739, tzinfo=utc), verbose_name='date_pendingUser_joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 1, 0, 36, 182463, tzinfo=utc), verbose_name='date_user_joined'),
        ),
    ]
