# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-18 01:35
from __future__ import unicode_literals

from django.db import migrations


def stub(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('myDream', '0025_auto_20170817_1800'),
    ]

    operations = [
        migrations.RunPython(stub),
    ]
