# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 04:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_paypaldb'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypaldb',
            name='first_name',
            field=models.CharField(default='na', max_length=50),
        ),
        migrations.AddField(
            model_name='paypaldb',
            name='last_name',
            field=models.CharField(default='na', max_length=50),
        ),
        migrations.AddField(
            model_name='paypaldb',
            name='payer_email',
            field=models.EmailField(default='j@j.com', max_length=254),
        ),
        migrations.AddField(
            model_name='paypaldb',
            name='payment_status',
            field=models.CharField(default='na', max_length=50),
        ),
        migrations.AddField(
            model_name='paypaldb',
            name='payment_type',
            field=models.CharField(default='na', max_length=50),
        ),
        migrations.AlterField(
            model_name='paypaldb',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 16, 4, 40, 42, 160121, tzinfo=utc), verbose_name='date_user_joined'),
        ),
    ]
