# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 05:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20161215_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypaldb',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 16, 5, 3, 33, 982342, tzinfo=utc), verbose_name='date_user_joined'),
        ),
    ]
