# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 06:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20161215_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypaldb',
            name='ipn_track_id',
            field=models.CharField(default='na', max_length=50),
        ),
        migrations.AlterField(
            model_name='paypaldb',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 16, 6, 7, 3, 451988, tzinfo=utc), verbose_name='date_user_joined'),
        ),
    ]
