# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 01:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20161216_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paypaldb',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='paypaldb',
            name='payment_type',
        ),
        migrations.AlterField(
            model_name='paypaldb',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 17, 1, 47, 34, 505479, tzinfo=utc), verbose_name='date_user_joined'),
        ),
    ]
