# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 02:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20161216_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypaldb',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 17, 2, 51, 5, 158967, tzinfo=utc), verbose_name='date_of_purchase'),
        ),
    ]
