# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 04:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import sales.jsonfield.fields
import sales.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20161216_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paypaltestdb',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='paypaltestdb',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='paypaltestdb',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 17, 4, 24, 14, 513710, tzinfo=utc), verbose_name='date_of_purchase'),
        ),
        migrations.AddField(
            model_name='paypaltestdb',
            name='ipn_track_id',
            field=models.CharField(default='na', max_length=50),
        ),
        migrations.AddField(
            model_name='paypaltestdb',
            name='txn_info',
            field=sales.jsonfield.fields.JSONField(default=sales.models.txn_default, verbose_name='transaction_info'),
        ),
        migrations.AlterField(
            model_name='paypaldb',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 17, 4, 24, 14, 512362, tzinfo=utc), verbose_name='date_of_purchase'),
        ),
        migrations.AlterField(
            model_name='paypaltestdb',
            name='first_name',
            field=models.CharField(default='na', max_length=50),
        ),
        migrations.AlterField(
            model_name='paypaltestdb',
            name='last_name',
            field=models.CharField(default='na', max_length=50),
        ),
        migrations.AlterField(
            model_name='paypaltestdb',
            name='payer_email',
            field=models.EmailField(default='j@j.com', max_length=254),
        ),
    ]
