# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 01:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_auto_20161216_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypaldb',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 8, 1, 16, 11, 6384, tzinfo=utc), verbose_name='date_of_purchase'),
        ),
        migrations.AlterField(
            model_name='paypaltestdb',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 8, 1, 16, 11, 7292, tzinfo=utc), verbose_name='date_of_purchase'),
        ),
    ]
