# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 22:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_auto_20170107_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.EmailField(default='m@m.com', max_length=254)),
                ('first_name', models.CharField(default='Super Client', max_length=50)),
                ('last_name', models.CharField(default='na', max_length=50)),
                ('created', models.DateTimeField(default=datetime.datetime(2017, 1, 9, 22, 55, 11, 993363, tzinfo=utc), verbose_name='clients_first_purchase')),
            ],
        ),
        migrations.AlterField(
            model_name='paypaldb',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 9, 22, 55, 11, 994865, tzinfo=utc), verbose_name='date_of_purchase'),
        ),
        migrations.AlterField(
            model_name='paypaltestdb',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 9, 22, 55, 11, 996084, tzinfo=utc), verbose_name='date_of_purchase'),
        ),
    ]
