# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 01:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_auto_20170109_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdb',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 11, 1, 57, 9, 766139, tzinfo=utc), verbose_name='clients_first_purchase'),
        ),
        migrations.AlterField(
            model_name='paypaldb',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 11, 1, 57, 9, 769441, tzinfo=utc), verbose_name='date_of_purchase'),
        ),
        migrations.AlterField(
            model_name='paypaltestdb',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 11, 1, 57, 9, 771758, tzinfo=utc), verbose_name='date_of_purchase'),
        ),
    ]
