# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 21:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_auto_20170110_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdb',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 11, 21, 55, 34, 296919, tzinfo=utc), verbose_name='clients_first_purchase'),
        ),
        migrations.AlterField(
            model_name='paypaldb',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 11, 21, 55, 34, 297905, tzinfo=utc), verbose_name='date_of_purchase'),
        ),
        migrations.AlterField(
            model_name='paypaltestdb',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 11, 21, 55, 34, 298678, tzinfo=utc), verbose_name='date_of_purchase'),
        ),
    ]
