# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-21 01:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_auto_20170111_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdb',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 21, 1, 4, 0, 659385, tzinfo=utc), verbose_name='clients_first_purchase'),
        ),
        migrations.AlterField(
            model_name='paypaldb',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 21, 1, 4, 0, 660458, tzinfo=utc), verbose_name='date_of_purchase'),
        ),
        migrations.AlterField(
            model_name='paypaltestdb',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 21, 1, 4, 0, 661207, tzinfo=utc), verbose_name='date_of_purchase'),
        ),
    ]
